spring:
  application:
    name: stoa
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: servitus
              uri: ${servitus.uri}
              predicates:
                - Path=/servitus/**
              filters:
                - RewritePath=/servitus/(?<segment>.*), /${segment}
                - TokenRelay=
            - id: rogator
              uri: ${rogator.uri}
              predicates:
                - Path=/rogator/**
              filters:
                - RewritePath=/rogator/(?<segment>.*), /${segment}
                - TokenRelay=
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins:
                  - http://localhost:4200
                  - http://localhost:4201
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - Authorization
                  - Content-Type
                exposedHeaders:
                  - Authorization
                maxAge: 3600

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: issuer
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: stoa
  datasource:
    driver-class-name: org.postgresql.Driver
    url: database-url
    username: database-username
    password: database-password
    hikari:
      connection-init-sql: SET search_path TO stoa
      max-lifetime: 480000            #8m
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000            #5m
      keepalive-time: 120000          #2m
      connection-timeout: 30000       #30s
  profiles:
    active: local #hetzner-test
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: stoa

app:
  openapi:
    gatewayUrl:
  cors:
    allowedOrigins:
      - http://localhost:4201
      - http://localhost:4200
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowedHeaders:
      - Authorization
      - Content-Type
    maxAge: 3600
    allow-credentials: false

keycloak:
  auth-server-url: https://my-keycloak/realms/my-realm
  realm: my-realm
  admin:
    client-id: admin-provisioner
    client-secret: my-client-secret
  client-id: my-client-id
  employee-role: EMPLOYEE


management:
  endpoints:
    web:
      exposure:
        include: "*"