servitus:
  uri: https://servitus.onrender.com

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: servitus
        url: /servitus/v3/api-docs
      #- name: rogator
      #  url: /rogator/v3/api-docs

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE

app:
  openapi:
    gatewayUrl: "https://servitus.onrender.com"
  cors:
    allowed-origins:
      - "http://localhost:4200"