server:
  port: 8094

spring:
  application:
    name: stoa
  cloud:
    gateway:
      routes:
        - id: servitus
          uri: http://localhost:8090
          predicates:
            - Path=/servitus/**
          filters:
            - RewritePath=/servitus/(?<segment>.*), /${segment}
        - id: rogator
          uri: http://localhost:8091
          predicates:
            - Path=/rogator/**
          filters:
            - RewritePath=/rogator/(?<segment>.*), /${segment}

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE